version: '3.8'

services:
  app:
    build: .
    container_name: rapidshelf_bff
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      JWT_SECRET: d14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42f
    depends_on:
      oracle-db:
        condition: service_healthy

  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle_db
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/oracle@localhost:1521/FREEPDB1 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  oracle_data: